// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXaRZRgjh0O4YpmhtcY_FmSTLnkFfNGH8',
    appId: '1:23111155461:android:64cf133e65a4c6556a416c',
    messagingSenderId: '23111155461',
    projectId: 'abencerrajes-app',
    storageBucket: 'abencerrajes-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnGUOhZadOCNYEOEK7SWcJR17GPdTtxDo',
    appId: '1:23111155461:web:c042f7c2ef98132b6a416c',
    messagingSenderId: '23111155461',
    projectId: 'abencerrajes-app',
    authDomain: 'abencerrajes-app.firebaseapp.com',
    storageBucket: 'abencerrajes-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjwiMbVdhv1-GRFbP_WSBBt-XjG8ank8g',
    appId: '1:23111155461:ios:17f650630b3ff2aa6a416c',
    messagingSenderId: '23111155461',
    projectId: 'abencerrajes-app',
    storageBucket: 'abencerrajes-app.firebasestorage.app',
    iosBundleId: 'com.example.abenceapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjwiMbVdhv1-GRFbP_WSBBt-XjG8ank8g',
    appId: '1:23111155461:ios:17f650630b3ff2aa6a416c',
    messagingSenderId: '23111155461',
    projectId: 'abencerrajes-app',
    storageBucket: 'abencerrajes-app.firebasestorage.app',
    iosBundleId: 'com.example.abenceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnGUOhZadOCNYEOEK7SWcJR17GPdTtxDo',
    appId: '1:23111155461:web:599648d8ceff334f6a416c',
    messagingSenderId: '23111155461',
    projectId: 'abencerrajes-app',
    authDomain: 'abencerrajes-app.firebaseapp.com',
    storageBucket: 'abencerrajes-app.firebasestorage.app',
  );

}